name: benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  benchmark:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-2.091.0

      - name: Run benchmarks with DMD
        run: |
          dub build --build release --single --compiler=dmd counter_speedy_stdio.d
          dub build --build release --single --compiler=dmd counter_speedy_fakestdio.d
          dub build --build release --single --compiler=dmd counter_std_stdio.d
          time ./counter_speedy_stdio > /dev/null
          time ./counter_speedy_stdio > /dev/null
          time ./counter_speedy_stdio > /dev/null
          time ./counter_speedy_fakestdio > /dev/null
          time ./counter_speedy_fakestdio > /dev/null
          time ./counter_speedy_fakestdio > /dev/null
          time ./counter_std_stdio > /dev/null
          time ./counter_std_stdio > /dev/null
          time ./counter_std_stdio > /dev/null
          dub list | grep speedy

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-1.30.0

      - name: Run benchmarks with LDC
        run: |
          dub build --build release --single --compiler=ldc2 counter_speedy_stdio.d
          dub build --build release --single --compiler=ldc2 counter_speedy_fakestdio.d
          dub build --build release --single --compiler=ldc2 counter_std_stdio.d
          time ./counter_speedy_stdio > /dev/null
          time ./counter_speedy_stdio > /dev/null
          time ./counter_speedy_stdio > /dev/null
          time ./counter_speedy_fakestdio > /dev/null
          time ./counter_speedy_fakestdio > /dev/null
          time ./counter_speedy_fakestdio > /dev/null
          time ./counter_std_stdio > /dev/null
          time ./counter_std_stdio > /dev/null
          time ./counter_std_stdio > /dev/null
          dub list | grep speedy

#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Save benchmark results
