# based on https://github.com/dlang-community/setup-dlang/issues/35#issuecomment-1241901601
#
# GDC 9.2.1 is used by AtCoder (linux64)
# GDC 11 is used by CodeChef (linux64)

name: gdc
on: [push, pull_request]

jobs:
  test:
    name: dub
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        dc: [ gdc-9, gdc-11 ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install DMD (so dub is available)
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install libev-dev libevent-dev libsqlite3-dev -y

      - name: Install ${{ matrix.dc }}
        run: |
          sudo apt-get update
          sudo apt-get install ${{ matrix.dc }} -y

      - name: Show version
        run: |
          ${{ matrix.dc }} --version
          dub --version

      - name: Run 64-bit tests
        env:
          DC: ${{ matrix.dc }}
        run: dub test -a x86_64 --compiler=${{ matrix.dc }}

      - name: Run mtfuzzer
        run: |
          ${{ matrix.dc }} -O2 -frelease -o mtfuzzer tests/mtfuzzer.d speedy/stdio.d speedy/fakestdio.d
          ./mtfuzzer speedy.stdio 1000 | ./mtfuzzer checker 1000
          ./mtfuzzer mixed 1000 | ./mtfuzzer checker 1000
          ./mtfuzzer speedy.fakestdio 100 | ./mtfuzzer checker 100
