# DMD 2.091.0 is used by Codeforces (win32)
# DMD 2.091.0 is used by AtCoder (linux64)
# LDC 1.20.1 is used by AtCoder (linux64)

name: main
on: [push, pull_request]

jobs:
  test:
    name: dub
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [dmd-latest, ldc-latest, dmd-2.091.0, ldc-1.20.1]
        exclude:
          - { os: macOS-latest, dc: dmd-2.091.0 }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Show version
        run: dub --version

      - name: Run 64-bit tests
        run: dub test -a x86_64

      - name: Run 32-bit tests
        if: matrix.os == 'windows-latest'
        run: dub test -a x86
